from app.domain.entities.Role import Role
from app.domain.entities.Event import Event
from app.infrastructure.db.connection import Base
from app.domain.entities.MenuOption import MenuOption
from app.domain.entities.EventTopic import EventTopic
from app.domain.entities.Competency import Competency
from app.domain.entities.Attendance import Attendance
from app.domain.entities.EventStatus import EventStatus
from app.domain.entities.PersonnelType import PersonnelType
from app.domain.entities.EventCategory import EventCategory
from app.domain.entities.SolutionCenter import SolutionCenter
from app.domain.entities.RoleMenuOption import RoleMenuOption
from app.domain.entities.ApplicationUser import ApplicationUser
from app.domain.entities.EventCompetency import EventCompetency
from app.domain.entities.AssistanceReason import AssistanceReason
from app.domain.entities.AttendancePerson import AttendancePerson
from app.domain.entities.ApplicationUserRole import ApplicationUserRole
from app.domain.entities.SpecificTrainingProgram import SpecificTrainingProgram