from sqlalchemy import Boolean, Column, Date, DateTime, ForeignKey, Integer, String, Text, Time
from app.infrastructure.db.connection import Base
from sqlalchemy.orm import relationship

class Event(Base):
    __tablename__ = "Event"

    IdEvent = Column(Integer, primary_key=True, autoincrement=True)
    titleEvent = Column(String(200), nullable=False)
    descriptionEvent = Column(Text, nullable=True)
    dateEvent = Column(Date, nullable=False)
    durationEvent = Column(String(50), nullable=True)
    startTimeEvent = Column(Time, nullable=False)
    endTimeEvent = Column(Time, nullable=False)
    IdSolutionCenter = Column(Integer, ForeignKey("SolutionCenter.IdSolutionCenter"), nullable=True)
    IdAssistanceReason = Column(Integer, ForeignKey("AssistanceReason.IdAssistanceReason"), nullable=True)
    IdSpecificTrainingProgram = Column(Integer, ForeignKey("SpecificTrainingProgram.IdSpecificTrainingProgram"), nullable=True)
    IdEventCategory = Column(Integer, ForeignKey("EventCategory.IdEventCategory"), nullable=True)
    IdEventStatus = Column(Integer, ForeignKey("EventStatus.IdEventStatus"), nullable=False)
    facilitatorNameEvent = Column(String(200), nullable=True)
    facilitatorCompanyEvent = Column(String(200), nullable=True)
    facilitatorPositionEvent = Column(String(150), nullable=True)
    secondFacilitatorNameEvent = Column(String(200), nullable=True)
    secondFacilitatorCompanyEvent = Column(String(200), nullable=True)
    secondFacilitatorPositionEvent = Column(String(150), nullable=True)
    scheduledPeopleNumber = Column(Integer, nullable=True)
    attendedPeopleNumber = Column(Integer, nullable=True)
    observationsEvent = Column(Text, nullable=True)
    eventPlace = Column(String(200), nullable=True)
    attendanceStartDateTime = Column(DateTime, nullable=False)
    attendanceEndDateTime = Column(DateTime, nullable=False)
    tokenEvent = Column(String(100), nullable=False, unique=True)
    publicUrlEvent = Column(String(500), nullable=True)
    qrPathEvent = Column(String(500), nullable=True)
    pensumOriginalNameEvent = Column(String(255), nullable=True)
    pensumPathEvent = Column(String(500), nullable=True)
    pensumMimeTypeEvent = Column(String(150), nullable=True)
    pensumSizeEvent = Column(Integer, nullable=True)
    isPaidTrainingEvent = Column(Boolean, nullable=False, default=False)
    isNewStaffInductionEvent = Column(Boolean, nullable=False, default=False)
    createdByUserLogin = Column(String(100), nullable=False)
    updatedByUserLogin = Column(String(100), nullable=True)
    createdAt = Column(DateTime, nullable=True)
    updatedAt = Column(DateTime, nullable=True)

    solutionCenter = relationship("SolutionCenter")
    assistanceReason = relationship("AssistanceReason")
    specificTrainingProgram = relationship("SpecificTrainingProgram")
    eventCategory = relationship("EventCategory")
    eventStatus = relationship("EventStatus")
    topics = relationship("EventTopic", back_populates="event", cascade="all, delete-orphan")
    competencies = relationship("EventCompetency", back_populates="event", cascade="all, delete-orphan")
    attendances = relationship("Attendance", back_populates="event", cascade="all, delete-orphan")